replicaCount: 1

vi_backend_image:
  image: 851725552187.dkr.ecr.eu-central-1.amazonaws.com/vi-service1:0.0.1
  image_2: 851725552187.dkr.ecr.eu-central-1.amazonaws.com/vi-service2:0.0.1
  pullPolicy: Always
  cpu: 500m
  memory: 512Mi
  ports:
    - name: node
      containerPort: 3000
      protocol: TCP
  ports_2:
    - name: node
      containerPort: 3001
      protocol: TCP
  env:
    - name: MONGODB_URL
      value: mongodb://viadmin:<PASS>@my-docdb-cluster.cluster-cxck4wwkgz1a.eu-central-1.docdb.amazonaws.com:27017/?replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
