apiVersion: v1
kind: Service
metadata:
  name: vi1
spec:
  selector:
    app: vi1
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 3010
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: vi2
spec:
  selector:
    app: vi2
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 3011
      targetPort: 3001